apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: istio-addons
  namespace: istio-system
spec:
  profile: demo
  components:
    prometheus:
      enabled: true
    kiali:
      enabled: true
    jaeger:
      enabled: true
  values:
    prometheus:
      enabled: true
      scrapeInterval: 15s
    kiali:
      enabled: true
      dashboard:
        prometheusUrl: http://prometheus.istio-system:9090
    tracing:
      enabled: true
      jaeger:
        sampling: 100
