version: '3.8'
services:
  webapp:
    build: .
    ports:
      - "5001:5000"
    environment:
      # --- Change this value to test different versions ---
      - APP_VERSION=1
      # --- DB Credentials for v3 ---
      - DB_HOST=postgres_db
      - DB_USER=myuser
      - DB_PASSWORD=mypassword
      - DB_NAME=mydatabase
    depends_on:
      - postgres_db

  postgres_db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=mydatabase
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: