services:
  webapp:
    build: .
    ports:
      - "5001:5000"
    environment:
      - APP_VERSION=3
      # --- DB Credentials for v3 ---
      - DB_HOST=postgres_db
      - DB_USER=antuser
      - DB_PASSWORD=The#Ant#Demo#5001
      - DB_NAME=antdemo
    depends_on:
      - postgres_db

  postgres_db:
    image: postgres:16-alpine
    environment:
      - POSTGRES_USER=antuser
      - POSTGRES_PASSWORD=The#Ant#Demo#5001
      - POSTGRES_DB=antdemo
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
