# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: logging_service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'logging_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15logging_service.proto\x12\x07logging\"\x1d\n\nLogRequest\x12\x0f\n\x07message\x18\x01 \x01(\t\">\n\x0bLogResponse\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x12\n\ncreated_at\x18\x03 \x01(\t\"\x1f\n\x0eGetLogsRequest\x12\r\n\x05limit\x18\x01 \x01(\x05\"5\n\x0fGetLogsResponse\x12\"\n\x04logs\x18\x01 \x03(\x0b\x32\x14.logging.LogResponse2\x86\x01\n\x0eLoggingService\x12\x36\n\tCreateLog\x12\x13.logging.LogRequest\x1a\x14.logging.LogResponse\x12<\n\x07GetLogs\x12\x17.logging.GetLogsRequest\x1a\x18.logging.GetLogsResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'logging_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_LOGREQUEST']._serialized_start=34
  _globals['_LOGREQUEST']._serialized_end=63
  _globals['_LOGRESPONSE']._serialized_start=65
  _globals['_LOGRESPONSE']._serialized_end=127
  _globals['_GETLOGSREQUEST']._serialized_start=129
  _globals['_GETLOGSREQUEST']._serialized_end=160
  _globals['_GETLOGSRESPONSE']._serialized_start=162
  _globals['_GETLOGSRESPONSE']._serialized_end=215
  _globals['_LOGGINGSERVICE']._serialized_start=218
  _globals['_LOGGINGSERVICE']._serialized_end=352
# @@protoc_insertion_point(module_scope)
