apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: user-service-policy
  namespace: ant-demo
  labels:
    app.kubernetes.io/name: user-service-policy
    app.kubernetes.io/part-of: ant-demo
spec:
  selector:
    matchLabels:
      app: ant-demo-user-service
  rules:
  - from:
    - source:
        principals:
        - "cluster.local/ns/ant-demo/sa/default"
    to:
    - operation:
        methods: ["GET", "POST", "PUT", "DELETE"]
        paths: ["/api/users/*"]
  - to:
    - operation:
        methods: ["GET"]
        paths: ["/"]
