apiVersion: apps/v1
kind: Deployment
metadata:
  name: ant-demo-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ant-demo
  template:
    metadata:
      labels:
        app: ant-demo
    spec:
      imagePullSecrets:
      - name: ghcr-creds
      containers:
      - name: webapp
        image: ghcr.io/moesix/ant-demo:v3
        ports:
        - containerPort: 5000
        env:
        - name: APP_VERSION
          value: "3"
        - name: DB_HOST
          value: "my-postgres-release-postgresql"
        - name: DB_NAME
          value: "antdemo"
        - name: DB_USER
          value: "antuser"
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-app-creds
              key: password