apiVersion: v1
kind: Service
metadata:
  name: ant-demo-webapp
  namespace: ant-demo
  labels:
    app: ant-demo-webapp
spec:
  type: ClusterIP
  ports:
  - port: 5000
    targetPort: 5000
    name: http
  selector:
    app: ant-demo-webapp
---
apiVersion: v1
kind: Service
metadata:
  name: ant-demo-user-service
  namespace: ant-demo
  labels:
    app: ant-demo-user-service
spec:
  type: ClusterIP
  ports:
  - port: 5000
    targetPort: 5000
    name: http
  - port: 50051
    targetPort: 50051
    name: grpc
  selector:
    app: ant-demo-user-service
---
apiVersion: v1
kind: Service
metadata:
  name: ant-demo-logging-service
  namespace: ant-demo
  labels:
    app: ant-demo-logging-service
spec:
  type: ClusterIP
  ports:
  - port: 5000
    targetPort: 5000
    name: http
  - port: 50052
    targetPort: 50052
    name: grpc
  selector:
    app: ant-demo-logging-service