# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: logging_service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'logging_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15logging_service.proto\x12\x07logging\"\x13\n\x11GetAllLogsRequest\"5\n\x12GetAllLogsResponse\x12\x1f\n\x04logs\x18\x01 \x03(\x0b\x32\x11.logging.LogEntry\"&\n\x15GetLogsByLevelRequest\x12\r\n\x05level\x18\x01 \x01(\t\"9\n\x16GetLogsByLevelResponse\x12\x1f\n\x04logs\x18\x01 \x03(\x0b\x32\x11.logging.LogEntry\"*\n\x17GetLogsByServiceRequest\x12\x0f\n\x07service\x18\x01 \x01(\t\";\n\x18GetLogsByServiceResponse\x12\x1f\n\x04logs\x18\x01 \x03(\x0b\x32\x11.logging.LogEntry\"V\n\x10\x43reateLogRequest\x12\x0f\n\x07service\x18\x01 \x01(\t\x12\r\n\x05level\x18\x02 \x01(\t\x12\x0f\n\x07message\x18\x03 \x01(\t\x12\x11\n\ttimestamp\x18\x04 \x01(\t\"3\n\x11\x43reateLogResponse\x12\x1e\n\x03log\x18\x01 \x01(\x0b\x32\x11.logging.LogEntry\"Z\n\x08LogEntry\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0f\n\x07service\x18\x02 \x01(\t\x12\r\n\x05level\x18\x03 \x01(\t\x12\x0f\n\x07message\x18\x04 \x01(\t\x12\x11\n\ttimestamp\x18\x05 \x01(\t2\xc7\x02\n\x0eLoggingService\x12\x45\n\nGetAllLogs\x12\x1a.logging.GetAllLogsRequest\x1a\x1b.logging.GetAllLogsResponse\x12Q\n\x0eGetLogsByLevel\x12\x1e.logging.GetLogsByLevelRequest\x1a\x1f.logging.GetLogsByLevelResponse\x12W\n\x10GetLogsByService\x12 .logging.GetLogsByServiceRequest\x1a!.logging.GetLogsByServiceResponse\x12\x42\n\tCreateLog\x12\x19.logging.CreateLogRequest\x1a\x1a.logging.CreateLogResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'logging_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GETALLLOGSREQUEST']._serialized_start=34
  _globals['_GETALLLOGSREQUEST']._serialized_end=53
  _globals['_GETALLLOGSRESPONSE']._serialized_start=55
  _globals['_GETALLLOGSRESPONSE']._serialized_end=108
  _globals['_GETLOGSBYLEVELREQUEST']._serialized_start=110
  _globals['_GETLOGSBYLEVELREQUEST']._serialized_end=148
  _globals['_GETLOGSBYLEVELRESPONSE']._serialized_start=150
  _globals['_GETLOGSBYLEVELRESPONSE']._serialized_end=207
  _globals['_GETLOGSBYSERVICEREQUEST']._serialized_start=209
  _globals['_GETLOGSBYSERVICEREQUEST']._serialized_end=251
  _globals['_GETLOGSBYSERVICERESPONSE']._serialized_start=253
  _globals['_GETLOGSBYSERVICERESPONSE']._serialized_end=312
  _globals['_CREATELOGREQUEST']._serialized_start=314
  _globals['_CREATELOGREQUEST']._serialized_end=400
  _globals['_CREATELOGRESPONSE']._serialized_start=402
  _globals['_CREATELOGRESPONSE']._serialized_end=453
  _globals['_LOGENTRY']._serialized_start=455
  _globals['_LOGENTRY']._serialized_end=545
  _globals['_LOGGINGSERVICE']._serialized_start=548
  _globals['_LOGGINGSERVICE']._serialized_end=875
# @@protoc_insertion_point(module_scope)
