apiVersion: v2
name: ant-demo
description: A Kubernetes cluster application showcase with Python Flask
type: application
version: 0.1.0
appVersion: "3"

dependencies:
  - name: postgresql
    version: 12.x.x
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled