apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: webapp-virtualservice
  namespace: ant-demo
  labels:
    app.kubernetes.io/name: webapp-virtualservice
    app.kubernetes.io/part-of: ant-demo
spec:
  hosts:
  - "*"
  gateways:
  - ant-demo-gateway
  http:
  - match:
    - uri:
        prefix: /api/webapp/
    route:
    - destination:
        host: ant-demo-webapp
        port:
          number: 5000
    retries:
      attempts: 3
      perTryTimeout: 2s
      retryOn: "5xx,connect-failure"
    fault:
      delay:
        fixedDelay: 500ms
        percentage:
          value: 10
  - match:
    - uri:
        exact: /
    - uri:
        prefix: /health
    route:
    - destination:
        host: ant-demo-webapp
        port:
          number: 5000
