# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from app.protos import logging_service_pb2 as logging__service__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in logging_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class LoggingServiceStub(object):
    """Logging service definition
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetAllLogs = channel.unary_unary(
                '/logging.LoggingService/GetAllLogs',
                request_serializer=logging__service__pb2.GetAllLogsRequest.SerializeToString,
                response_deserializer=logging__service__pb2.GetAllLogsResponse.FromString,
                _registered_method=True)
        self.GetLogsByLevel = channel.unary_unary(
                '/logging.LoggingService/GetLogsByLevel',
                request_serializer=logging__service__pb2.GetLogsByLevelRequest.SerializeToString,
                response_deserializer=logging__service__pb2.GetLogsByLevelResponse.FromString,
                _registered_method=True)
        self.GetLogsByService = channel.unary_unary(
                '/logging.LoggingService/GetLogsByService',
                request_serializer=logging__service__pb2.GetLogsByServiceRequest.SerializeToString,
                response_deserializer=logging__service__pb2.GetLogsByServiceResponse.FromString,
                _registered_method=True)
        self.CreateLog = channel.unary_unary(
                '/logging.LoggingService/CreateLog',
                request_serializer=logging__service__pb2.CreateLogRequest.SerializeToString,
                response_deserializer=logging__service__pb2.CreateLogResponse.FromString,
                _registered_method=True)


class LoggingServiceServicer(object):
    """Logging service definition
    """

    def GetAllLogs(self, request, context):
        """Get all logs
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetLogsByLevel(self, request, context):
        """Get logs by level
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetLogsByService(self, request, context):
        """Get logs by service
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateLog(self, request, context):
        """Create log entry
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LoggingServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetAllLogs': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAllLogs,
                    request_deserializer=logging__service__pb2.GetAllLogsRequest.FromString,
                    response_serializer=logging__service__pb2.GetAllLogsResponse.SerializeToString,
            ),
            'GetLogsByLevel': grpc.unary_unary_rpc_method_handler(
                    servicer.GetLogsByLevel,
                    request_deserializer=logging__service__pb2.GetLogsByLevelRequest.FromString,
                    response_serializer=logging__service__pb2.GetLogsByLevelResponse.SerializeToString,
            ),
            'GetLogsByService': grpc.unary_unary_rpc_method_handler(
                    servicer.GetLogsByService,
                    request_deserializer=logging__service__pb2.GetLogsByServiceRequest.FromString,
                    response_serializer=logging__service__pb2.GetLogsByServiceResponse.SerializeToString,
            ),
            'CreateLog': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateLog,
                    request_deserializer=logging__service__pb2.CreateLogRequest.FromString,
                    response_serializer=logging__service__pb2.CreateLogResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'logging.LoggingService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('logging.LoggingService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class LoggingService(object):
    """Logging service definition
    """

    @staticmethod
    def GetAllLogs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/logging.LoggingService/GetAllLogs',
            logging__service__pb2.GetAllLogsRequest.SerializeToString,
            logging__service__pb2.GetAllLogsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetLogsByLevel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/logging.LoggingService/GetLogsByLevel',
            logging__service__pb2.GetLogsByLevelRequest.SerializeToString,
            logging__service__pb2.GetLogsByLevelResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetLogsByService(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/logging.LoggingService/GetLogsByService',
            logging__service__pb2.GetLogsByServiceRequest.SerializeToString,
            logging__service__pb2.GetLogsByServiceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateLog(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/logging.LoggingService/CreateLog',
            logging__service__pb2.CreateLogRequest.SerializeToString,
            logging__service__pb2.CreateLogResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
