# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: user_service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'user_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12user_service.proto\x12\x05users\"\x14\n\x12GetAllUsersRequest\"1\n\x13GetAllUsersResponse\x12\x1a\n\x05users\x18\x01 \x03(\x0b\x32\x0b.users.User\"\x1c\n\x0eGetUserRequest\x12\n\n\x02id\x18\x01 \x01(\x05\",\n\x0fGetUserResponse\x12\x19\n\x04user\x18\x01 \x01(\x0b\x32\x0b.users.User\"B\n\x11\x43reateUserRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05\x65mail\x18\x02 \x01(\t\x12\x10\n\x08password\x18\x03 \x01(\t\"/\n\x12\x43reateUserResponse\x12\x19\n\x04user\x18\x01 \x01(\x0b\x32\x0b.users.User\"N\n\x11UpdateUserRequest\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\r\n\x05\x65mail\x18\x03 \x01(\t\x12\x10\n\x08password\x18\x04 \x01(\t\"/\n\x12UpdateUserResponse\x12\x19\n\x04user\x18\x01 \x01(\x0b\x32\x0b.users.User\"\x1f\n\x11\x44\x65leteUserRequest\x12\n\n\x02id\x18\x01 \x01(\x05\"%\n\x12\x44\x65leteUserResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\"W\n\x04User\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\r\n\x05\x65mail\x18\x03 \x01(\t\x12\x12\n\ncreated_at\x18\x04 \x01(\t\x12\x12\n\nupdated_at\x18\x05 \x01(\t2\xd6\x02\n\x0bUserService\x12\x44\n\x0bGetAllUsers\x12\x19.users.GetAllUsersRequest\x1a\x1a.users.GetAllUsersResponse\x12\x38\n\x07GetUser\x12\x15.users.GetUserRequest\x1a\x16.users.GetUserResponse\x12\x41\n\nCreateUser\x12\x18.users.CreateUserRequest\x1a\x19.users.CreateUserResponse\x12\x41\n\nUpdateUser\x12\x18.users.UpdateUserRequest\x1a\x19.users.UpdateUserResponse\x12\x41\n\nDeleteUser\x12\x18.users.DeleteUserRequest\x1a\x19.users.DeleteUserResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'user_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GETALLUSERSREQUEST']._serialized_start=29
  _globals['_GETALLUSERSREQUEST']._serialized_end=49
  _globals['_GETALLUSERSRESPONSE']._serialized_start=51
  _globals['_GETALLUSERSRESPONSE']._serialized_end=100
  _globals['_GETUSERREQUEST']._serialized_start=102
  _globals['_GETUSERREQUEST']._serialized_end=130
  _globals['_GETUSERRESPONSE']._serialized_start=132
  _globals['_GETUSERRESPONSE']._serialized_end=176
  _globals['_CREATEUSERREQUEST']._serialized_start=178
  _globals['_CREATEUSERREQUEST']._serialized_end=244
  _globals['_CREATEUSERRESPONSE']._serialized_start=246
  _globals['_CREATEUSERRESPONSE']._serialized_end=293
  _globals['_UPDATEUSERREQUEST']._serialized_start=295
  _globals['_UPDATEUSERREQUEST']._serialized_end=373
  _globals['_UPDATEUSERRESPONSE']._serialized_start=375
  _globals['_UPDATEUSERRESPONSE']._serialized_end=422
  _globals['_DELETEUSERREQUEST']._serialized_start=424
  _globals['_DELETEUSERREQUEST']._serialized_end=455
  _globals['_DELETEUSERRESPONSE']._serialized_start=457
  _globals['_DELETEUSERRESPONSE']._serialized_end=494
  _globals['_USER']._serialized_start=496
  _globals['_USER']._serialized_end=583
  _globals['_USERSERVICE']._serialized_start=586
  _globals['_USERSERVICE']._serialized_end=928
# @@protoc_insertion_point(module_scope)
